possum_names = ["Marcelo",
"Rei Arnold",
"Mãe de todos",
"Cata piolho",
"Fura bolo",
"Luna",
"Luisa",
"Luke",
"Ana Luisa",
"Dante",
"Aira Shiiratori",
"Comedor de cu",
"Hilbert",
"Mio",
"Jesus cristo",
"Menor da capital",
"MC Menor da VG",
"Casemiro",
"Aaron T",
"Aaron Z",
"Robaire",
"Taeyoug",
"Mafuyu asahina",
"Mika",
"Lottie",
"Rod",
"Currytano",
"Rit",
"Jesse",
"Marcos",
"Marcela",
"Pedro",
"Tristan",
"Sebastião",
"Charlote",
"Ramires",
"Coração Indomável",
"Dolores",
"Risca Faca",
"Reinaldo",
"Fura Bolo"
"Mãe de todos",
"Cata Piolho",
"Sonic",
"Mario",
"Luigi",
"Estrela",
"Corsa",
"Uno Mile",
"Alvin",
"Simon",
"Teodoro",
"Jimin",
"Jungkook",
"Kleber",
"Parto de Gêmeos",
"Pão de Alho",
"Pão de Queijo",
"Pão de Ló",
"Cacetinho",
"Média",
"Cacetão",
"Vitamina pras mulher virar muralha",
"Farelo de cavalo",
"Tanajura",
"Uma Folha de guardanapo",
"Alpiste",
"Duas Pipoca",
"Bis (com embalagem)",
"Folha de peão",
"Pampola",
"Unha cortada na hora",
"Fruto do peão",
"Ração de gato",
"Purina de cavalo",
"Café quente",
"Ameixa pôdi",
"Maçã pôdi",
"Pó de serra",
"Rei Ayanami",
"Asuka Langley Soryu",
"Shinji Ikari",
"Toji Suzuhara",
"Kaworu Nagisa",
"Mari Illustrious Makinami",
"Misato Katsuragi",
"Freddy Fazbear",
"Bonnie",
"Chica",
"Foxy",
"Phone Guy",
"Toy Freddy",
"Toy Bonnie",
"Toy Chica" ,
"Mangle",
"Balloon Boy",
"Jay-Jay",
"The Puppet",
"Shadow Bonnie",
"Withered Bonnie",
"Golden Freddy",
"Withered Chica",
"Springtrap",
"Phantom Freddy",
"Phantom Balloon Boy",
"Phantom Mangle",
"Nightmare Freddy",
"Nightmare Bonnie",
"Nightmare Chica",
"Plushtrap",
"Nightmare Fredbear",
"Nightmare",
"Jack O' Chica",
"Nightmare Mangle",
"Nightmarionne",
"Nightmare Balloon Boy",
"Fredbear",]

categoria_names = "filme, série, jogo, música, anime"

kinass_game_names = [

    "ingo",
    "Mettaton (Undertale) https://static.wikia.nocookie.net/undertale-determination/images/5/58/Mettaton.gif/revision/latest?cb=20160424231856&path-prefix=pt-br",
    "Akito Shinonome (Project SEKAI) https://static.wikia.nocookie.net/projectsekai/images/1/19/Well-Known_Big_Shot.png/revision/latest/scale-to-width-down/2000?cb=20201101205554",
    "Ena Shinonome (Project SEKAI) https://static.wikia.nocookie.net/projectsekai/images/8/83/SNS-Addicted_Artist.png/revision/latest/scale-to-width-down/2000?cb=20201102133345",
    "Ichika Hoshino (Project SEKAI) https://static.wikia.nocookie.net/projectsekai/images/b/b3/Ichika.png/revision/latest?cb=20200213203809",
    "Maya Yamato (BanG Dream! Girls Band Party) http://pm1.narvii.com/6929/b453e660b1f445a407426fc610403bb4a4dc4c80r1-1334-1002v2_uhq.jpg",
    "Steve (Minecraft) https://www.altoastral.com.br/media/_versions/legacy/2016/07/VENON_widexl.jpg",
    "Nagito Komaeda (Danganronpa) https://criadoresid.com/wp-content/uploads/2020/04/Goularte-300x300.png",
    "Kokichi Ouma (Danganronpa) https://static.wikia.nocookie.net/danganronpa/images/6/66/Kokichi_Oma_Ouma_Illustration.png/revision/latest?cb=20180925005631",
    "HiMERU (Ensemble Stars!!) https://static.wikia.nocookie.net/ensemble-stars/images/1/13/HiMERU_4.png/revision/latest?cb=20191109185420",
    "Rei Sakuma (Ensemble Stars!!) https://i1.sndcdn.com/artworks-D1XHyHGJvmLzIY8a-oD5Uag-t500x500.jpg",
    "Kirby (Kirby Series) https://t.ctcdn.com.br/QeslF547VV1x4xajMXJ8VESek2U=/512x288/smart/filters:format(webp)/i560209.jpeg",
    "Sonic (Sonic The Hedghog Series) https://s2.glbimg.com/xiVTwrx3V58sFmcMvMg50OoJk-w=/0x0:1400x1000/600x0/smart/filters:gifv():strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2019/w/8/zxJkbATbKUBGlJ0tGseA/sonic.jpg",
    "Ayato (Gayshin Impact) https://br.atsit.in/wp-content/uploads/2022/02/data-de-lancamento-do-genshin-impact-ayato.jpg",
    "Freddybear (Five Night's At Freddy's Series) http://images7.memedroid.com/images/UPLOADED594/61534311cf415.jpeg",
    "O Cachorro Homofobico (Homophobic Dog Thread) https://cdn.discordapp.com/attachments/747251698040569971/965118837303439410/image0.jpg",
    "Pato donald (Kingdom Hearts Series) https://cdn.vox-cdn.com/thumbor/cRwU8vHcDNMSAop_BAgRpB_DIeE=/42x107:612x405/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/13627056/Screen_Shot_2018_12_14_at_12.49.46_PM.png",
    "Charlotte (Hello Charlotte Series) https://static.wikia.nocookie.net/hellocharlotte/images/7/72/Charlotte1-1.png/revision/latest?cb=20170417073831",
    "Charles Eyler (Hello Charlotte Series) https://static.wikia.nocookie.net/hellocharlotte/images/4/4c/Charles_neutral.png/revision/latest?cb=20180928203204",
    "Joker (Persona 5) https://images.uncyc.org/pt/8/88/Jokerpersona5.jpg",
    "Joker (Batman Arkham ACK) https://i.ytimg.com/vi/x6cz4rkfdDM/maxresdefault.jpg",
    "Akechi Goro (Shin Megami Tensei) https://static.wikia.nocookie.net/megamitensei/images/b/bd/P5A_Goro_Akechi.png/revision/latest?cb=20180421175225",
    "Bayonetta (Bayonetta) https://uploads.jovemnerd.com.br/wp-content/uploads/2021/09/bayonetta-3-atualizacao-hideki-kamiya.jpg",
    "Lucina (Fire Emblem) https://static.wikia.nocookie.net/fireemblem/images/d/d0/Lucina_official_art.png/revision/latest?cb=20191103195341",
    "Edelgard (Fire Emblem) https://static.wikia.nocookie.net/fireemblem/images/7/7b/Artwork_Edelgard.png/revision/latest?cb=20201220085222",
    "Miles Edgeworth (Pheonix Wright Series) https://static.wikia.nocookie.net/aceattorney/images/a/af/Miles_Edgeworth_4_PLvsAA.png/revision/latest?cb=20140413023019",
    "Rinne Amagi (Ensemble Stars!!) https://static.wikia.nocookie.net/ensemble-stars/images/f/f5/Rinne_Amagi_Casual_Spring-Summer_Dialogue_Render.png/revision/latest?cb=20200725134806",
    "Ibara Saegusa (Ensemble Stars!!) https://static1.purepeople.com.br/articles/1/31/54/71/@/3562764-no-bbb-21-fiuk-levou-bronca-ao-vivo-d-624x600-2.jpg",
    "Masahiro Sakurai (Caetano Series) http://images3.memedroid.com/images/UPLOADED851/617ed7b3dc9a1.jpeg",
    "Nana Daiba (Revue Starlight) https://static.wikia.nocookie.net/revuestarlight/images/1/1f/Nana_Daiba_Revue_Outfit.png/revision/latest?cb=20180726154821"
]

kinass_anim_names = kinass_game_names